/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class MainFrame extends javax.swing.JFrame {
 private DefaultListModel<String> resepListModel;

    /**
     * Creates new form MainFrame
     */
 
    public MainFrame() {
        initComponents();
        resepListModel = new DefaultListModel<>();
        listResep.setModel(resepListModel);
        
    }


   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNamaResep = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLangkah = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listResep = new javax.swing.JList<>();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("Aplikasi Resep Masakan");

        txtNamaResep.setBackground(new java.awt.Color(153, 153, 153));
        txtNamaResep.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N

        txtLangkah.setBackground(new java.awt.Color(153, 153, 153));
        txtLangkah.setColumns(20);
        txtLangkah.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        txtLangkah.setRows(5);
        jScrollPane1.setViewportView(txtLangkah);

        listResep.setBackground(new java.awt.Color(153, 153, 153));
        listResep.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        listResep.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listResep);

        btnTambah.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(759, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNamaResep, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(534, 534, 534))))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnTambah)
                .addGap(87, 87, 87)
                .addComponent(btnUbah)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton1)
                        .addGap(97, 97, 97)
                        .addComponent(btnHapus)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNamaResep, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus)
                            .addComponent(jButton1))
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
      System.out.println("Tombol Tambah Ditekan!");
    String namaResep = txtNamaResep.getText();
    String bahanLangkah = txtLangkah.getText();

    if (!namaResep.isEmpty() && !bahanLangkah.isEmpty()) {
        String resep = namaResep + ":\n" + bahanLangkah;
        resepListModel.addElement(resep);

        txtNamaResep.setText("");
        txtLangkah.setText("");
        JOptionPane.showMessageDialog(this, "Resep berhasil ditambahkan!");
    } else {
        JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!");
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
       int selectedIndex = listResep.getSelectedIndex();
    if (selectedIndex != -1) {
        String namaResep = txtNamaResep.getText();
        String bahanLangkah = txtLangkah.getText();

        if (!namaResep.isEmpty() && !bahanLangkah.isEmpty()) {
            String resep = namaResep + ":\n" + bahanLangkah;
            resepListModel.set(selectedIndex, resep);
            JOptionPane.showMessageDialog(this, "Resep berhasil diubah!");
        } else {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih resep yang ingin diubah!");
    }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
       int selectedIndex = listResep.getSelectedIndex();
    if (selectedIndex != -1) {
        resepListModel.remove(selectedIndex);
        JOptionPane.showMessageDialog(this, "Resep berhasil dihapus!");
    } else {
        JOptionPane.showMessageDialog(this, "Pilih resep yang ingin dihapus!");
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        // Pilih lokasi file dengan JFileChooser
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        int option = fileChooser.showSaveDialog(this);

        if (option == javax.swing.JFileChooser.APPROVE_OPTION) {
            // Dapatkan file yang dipilih
            java.io.File file = fileChooser.getSelectedFile();

            // Gunakan FileWriter untuk menyimpan data
            try (java.io.FileWriter writer = new java.io.FileWriter(file)) {
                for (int i = 0; i < resepListModel.getSize(); i++) {
                    writer.write(resepListModel.get(i) + "\n\n"); // Tambahkan setiap resep
                }
                writer.flush();
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke file!");
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listResep;
    private javax.swing.JTextArea txtLangkah;
    private javax.swing.JTextField txtNamaResep;
    // End of variables declaration//GEN-END:variables
}
